#!/usr/bin/python
#
# apkx -- A Python wrapper for dex2jar and CFR. Use to extract and decompile Java code from Android APK.
# Because nobody likes messing with Java classpaths & command lines.
# v0.9.1
#
# Author: Bernhard Mueller
# This file is part of the OWASP Mobile Testing Guide (https://github.com/OWASP/owasp-mstg)
#
# See also:
#
# Dex2jar - https://github.com/pxb1988/dex2jar
# CFR - http://www.benf.org/other/cfr/
# 
# This program is free software: you can redistribute it and/or modify  
# it under the terms of the GNU General Public License as published by  
# the Free Software Foundation, version 3.

import os
import sys
import subprocess
import zipfile
import re
import argparse


def dextojar(converter, jar_path, ext_path):

	if (converter == 'dex2jar'):
		subprocess.call(['java', '-Xms512m', '-Xmx1024m', '-cp', jar_path, 'com.googlecode.dex2jar.tools.Dex2jarCmd', ext_path + '/' + file, '-o', ext_path + '/' + jar_filename, '-f'])


def decompile(decompiler, jar_path, ext_path):

	if (decompiler == 'cfr'):
		subprocess.call(['java','-Xms512m', '-Xmx1024m', '-cp', jar_path, 'org.benf.cfr.reader.Main', ext_path + '/' + jar_filename, '--outputdir', src_path, '--caseinsensitivefs', 'true', '--silent', 'true'])



'''
====== Main ======
'''

parser = argparse.ArgumentParser(description='Decompile an Android APK archive.')

parser.add_argument('-c', '--converter', help='Dex to jar conversion method (default: dex2jar)', choices=['dex2jar',], default = "dex2jar")
parser.add_argument('-d', '--decompiler', help='Decompiler backend to use (default: cfr)', choices=['cfr',], default = "cfr")
parser.add_argument('apkfile', help='File to decompile')

args = parser.parse_args()

'''
	Unzip the application package.
'''

ext_path = os.path.splitext(os.path.basename(args.apkfile))[0]
src_path = ext_path + "/src"

jar_path = os.path.dirname(os.path.realpath(__file__)) + "/apkx-libs.jar"

print("Extracting " + args.apkfile + " to " + ext_path)

try:
	zip_ref = zipfile.ZipFile(args.apkfile, 'r')
	zip_ref.extractall(ext_path)
	zip_ref.close()
except IOError as e:
	print("Error extracting apk: " + str(e))
	sys.exit(0)

'''
	Iterate over all .dex files
'''

for root, dirs, files in os.walk(ext_path):
	for file in files:
		if file.endswith((".dex")):
			jar_filename = os.path.splitext(file)[0] + ".jar"

			print('Converting: ' + file + ' -> ' + jar_filename)

			'''
				Conversion Step
			'''

			try:
				dextojar(args.converter, jar_path, ext_path)
			except Exception as e:
				print('Error converting dex to jar:'+ str(e))
				next

			'''
				Decompilation Step
			'''

			print("Decompiling to " + src_path)

			try:
				decompile(args.decompiler, jar_path, ext_path)
			except Exception as e:
				print('Error decompiling:' + str(e))


